spring:
  application:
    name: "@project.artifactId@"
  profiles:
    active: ${PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:council
    username: 
    password:
